services:
  app:
    build: .
    container_name: app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8100:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel
networks:
  laravel:
    driver: bridge